// @ts-check
// A single autogenerated sidebar built from the docs/ folder tree. Order comes from each file's
// `sidebar_position` frontmatter and each chapter folder's `_category_.json` — all written by
// sync-docs.mjs, so the sidebar reflects the repo's chapter/exercise structure automatically.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
